site_name: Blog fyrir snjallingar
site_description: Blog vefur fyrir áhugasama um snjallvæðingu heimila og fyrirtækja 
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/snjallingur_logo.png
nav:
  - Home: index.md